version: '3.2'

services:
  postgres-dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_DB: dev-example-api
      POSTGRES_PASSWORD: dev

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
      - ./configs:/usr/src/app/configs
    env_file:
      - .env.dev
    environment:
      - HTTP_PORT=3000
      - NODE_ENV=development
      - database__host=postgres-dev
      - database__port=5432
      - database__database=dev-example-api
      - database__username=dev_user
      - database__password=dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres-dev
